/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AluminiumWindowRepairPowaiRouteImport } from './routes/aluminium-window-repair-powai'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SlidingWindowRepairPowaiRouteImport } from './routes/sliding-window-repair-powai'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WindowRollerRepairPowaiRouteImport } from './routes/window-roller-repair-powai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AluminiumWindowRepairPowaiRoute =
  AluminiumWindowRepairPowaiRouteImport.update({
    id: '/aluminium-window-repair-powai',
    path: '/aluminium-window-repair-powai',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidingWindowRepairPowaiRoute =
  SlidingWindowRepairPowaiRouteImport.update({
    id: '/sliding-window-repair-powai',
    path: '/sliding-window-repair-powai',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowRollerRepairPowaiRoute = WindowRollerRepairPowaiRouteImport.update({
  id: '/window-roller-repair-powai',
  path: '/window-roller-repair-powai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluminium-window-repair-powai': typeof AluminiumWindowRepairPowaiRoute
  '/privacy': typeof PrivacyRoute
  '/sliding-window-repair-powai': typeof SlidingWindowRepairPowaiRoute
  '/terms': typeof TermsRoute
  '/window-roller-repair-powai': typeof WindowRollerRepairPowaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluminium-window-repair-powai': typeof AluminiumWindowRepairPowaiRoute
  '/privacy': typeof PrivacyRoute
  '/sliding-window-repair-powai': typeof SlidingWindowRepairPowaiRoute
  '/terms': typeof TermsRoute
  '/window-roller-repair-powai': typeof WindowRollerRepairPowaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluminium-window-repair-powai': typeof AluminiumWindowRepairPowaiRoute
  '/privacy': typeof PrivacyRoute
  '/sliding-window-repair-powai': typeof SlidingWindowRepairPowaiRoute
  '/terms': typeof TermsRoute
  '/window-roller-repair-powai': typeof WindowRollerRepairPowaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluminium-window-repair-powai'
    | '/privacy'
    | '/sliding-window-repair-powai'
    | '/terms'
    | '/window-roller-repair-powai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aluminium-window-repair-powai'
    | '/privacy'
    | '/sliding-window-repair-powai'
    | '/terms'
    | '/window-roller-repair-powai'
  id:
    | '__root__'
    | '/'
    | '/aluminium-window-repair-powai'
    | '/privacy'
    | '/sliding-window-repair-powai'
    | '/terms'
    | '/window-roller-repair-powai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AluminiumWindowRepairPowaiRoute: typeof AluminiumWindowRepairPowaiRoute
  PrivacyRoute: typeof PrivacyRoute
  SlidingWindowRepairPowaiRoute: typeof SlidingWindowRepairPowaiRoute
  TermsRoute: typeof TermsRoute
  WindowRollerRepairPowaiRoute: typeof WindowRollerRepairPowaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluminium-window-repair-powai': {
      id: '/aluminium-window-repair-powai'
      path: '/aluminium-window-repair-powai'
      fullPath: '/aluminium-window-repair-powai'
      preLoaderRoute: typeof AluminiumWindowRepairPowaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sliding-window-repair-powai': {
      id: '/sliding-window-repair-powai'
      path: '/sliding-window-repair-powai'
      fullPath: '/sliding-window-repair-powai'
      preLoaderRoute: typeof SlidingWindowRepairPowaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-roller-repair-powai': {
      id: '/window-roller-repair-powai'
      path: '/window-roller-repair-powai'
      fullPath: '/window-roller-repair-powai'
      preLoaderRoute: typeof WindowRollerRepairPowaiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AluminiumWindowRepairPowaiRoute: AluminiumWindowRepairPowaiRoute,
  PrivacyRoute: PrivacyRoute,
  SlidingWindowRepairPowaiRoute: SlidingWindowRepairPowaiRoute,
  TermsRoute: TermsRoute,
  WindowRollerRepairPowaiRoute: WindowRollerRepairPowaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
